import { useEffect, useState } from "react";
import { api, type PurchaseOrder } from "../api";
import Pagination from "./Pagination";

const LIMIT = 50;

export default function PurchaseOrdersTable() {
  const [rows, setRows] = useState<PurchaseOrder[]>([]);
  const [total, setTotal] = useState(0);
  const [offset, setOffset] = useState(0);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    api
      .purchaseOrders({ limit: LIMIT, offset })
      .then((res) => {
        setRows(res.rows);
        setTotal(res.total);
      })
      .finally(() => setLoading(false));
  }, [offset]);

  return (
    <div>
      <div className="panel-header">
        <h2>Purchase Orders (planned)</h2>
      </div>
      <p className="muted">Generated by the last planning run, one per (item, supplier) shortfall.</p>
      <table className="data-table">
        <thead>
          <tr>
            <th>PO</th>
            <th>Supplier</th>
            <th>Status</th>
            <th>Item</th>
            <th>Qty</th>
            <th>Due Date</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r) =>
            r.lines.map((line, i) => (
              <tr key={`${r.po_id}-${i}`}>
                {i === 0 && (
                  <>
                    <td rowSpan={r.lines.length}>{r.po_id}</td>
                    <td rowSpan={r.lines.length}>{r.supplier_id ?? "-"}</td>
                    <td rowSpan={r.lines.length}>
                      <span className={`badge badge-${r.status.toLowerCase()}`}>{r.status}</span>
                    </td>
                  </>
                )}
                <td>{line.item_id}</td>
                <td>{line.qty}</td>
                <td>{line.due_date}</td>
              </tr>
            )),
          )}
        </tbody>
      </table>
      {loading && <div className="loading">Loading...</div>}
      {!loading && rows.length === 0 && <div className="muted">No purchase orders yet — run planning from the Overview tab.</div>}
      <Pagination offset={offset} limit={LIMIT} total={total} onOffsetChange={setOffset} />
    </div>
  );
}
