"""add projected_end to work orders

Revision ID: 3b40fd5d1733
Revises: 5af0526a1c9e
Create Date: 2026-08-22 15:51:42.521033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b40fd5d1733'
down_revision: Union[str, Sequence[str], None] = '5af0526a1c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('projected_end', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'projected_end')
    # ### end Alembic commands ###
