"""add contract/quoted value to projects

Revision ID: 3cf05d6f1c62
Revises: b701f93ba9a3
Create Date: 2026-08-12 18:15:04.675694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf05d6f1c62'
down_revision: Union[str, Sequence[str], None] = 'b701f93ba9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('contract_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('projects', sa.Column('quoted_value', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'quoted_value')
    op.drop_column('projects', 'contract_value')
    # ### end Alembic commands ###
