"""add pegging columns, plan exceptions and actions

Revision ID: 47bc518fc526
Revises: 3cf05d6f1c62
Create Date: 2026-08-22 15:24:03.496408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47bc518fc526'
down_revision: Union[str, Sequence[str], None] = '3cf05d6f1c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_actions',
    sa.Column('action_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.Enum('EXPEDITE', 'RESCHEDULE', 'CHANGE_PRIORITY', 'RELEASE', 'CANCEL', 'ACKNOWLEDGE_EXCEPTION', 'SNOOZE_EXCEPTION', 'RESOLVE_EXCEPTION', 'ADJUST_CAPACITY', name='actiontype'), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=200), nullable=False),
    sa.Column('before_value', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('plan_exceptions',
    sa.Column('exception_id', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('PAST_DUE_WO_START', 'PAST_DUE_PO_RELEASE', 'CAPACITY_OVERLOAD', 'NO_ROUTING', 'BOM_DEPTH_EXCEEDED', 'UNKNOWN_ITEM', name='exceptioncategory'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='exceptionseverity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'SNOOZED', 'RESOLVED', name='exceptionstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('item_id', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('source_ref', sa.String(length=40), nullable=True),
    sa.Column('customer', sa.String(length=200), nullable=True),
    sa.Column('work_center_id', sa.String(length=20), nullable=True),
    sa.Column('days_late', sa.Integer(), nullable=False),
    sa.Column('value_at_risk', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('need_date', sa.Date(), nullable=True),
    sa.Column('snooze_until', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('exception_id')
    )
    op.create_index(op.f('ix_plan_exceptions_category'), 'plan_exceptions', ['category'], unique=False)
    op.create_index(op.f('ix_plan_exceptions_severity'), 'plan_exceptions', ['severity'], unique=False)
    op.create_index(op.f('ix_plan_exceptions_status'), 'plan_exceptions', ['status'], unique=False)
    op.add_column('purchase_orders', sa.Column('parent_wo_id', sa.String(length=30), nullable=True))
    op.add_column('purchase_orders', sa.Column('source', sa.Enum('PROJECT', 'AFTERMARKET', 'OVERHAUL', name='workordersource'), nullable=True))
    op.add_column('purchase_orders', sa.Column('source_ref', sa.String(length=30), nullable=True))
    op.add_column('purchase_orders', sa.Column('bom_level', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('purchase_orders', sa.Column('expedite_days', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_purchase_orders_parent_wo_id'), 'purchase_orders', ['parent_wo_id'], unique=False)
    op.add_column('work_orders', sa.Column('parent_wo_id', sa.String(length=30), nullable=True))
    op.add_column('work_orders', sa.Column('bom_level', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('work_orders', sa.Column('expedite_days', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_work_orders_parent_wo_id'), 'work_orders', ['parent_wo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_parent_wo_id'), table_name='work_orders')
    op.drop_column('work_orders', 'expedite_days')
    op.drop_column('work_orders', 'bom_level')
    op.drop_column('work_orders', 'parent_wo_id')
    op.drop_index(op.f('ix_purchase_orders_parent_wo_id'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'expedite_days')
    op.drop_column('purchase_orders', 'bom_level')
    op.drop_column('purchase_orders', 'source_ref')
    op.drop_column('purchase_orders', 'source')
    op.drop_column('purchase_orders', 'parent_wo_id')
    op.drop_index(op.f('ix_plan_exceptions_status'), table_name='plan_exceptions')
    op.drop_index(op.f('ix_plan_exceptions_severity'), table_name='plan_exceptions')
    op.drop_index(op.f('ix_plan_exceptions_category'), table_name='plan_exceptions')
    op.drop_table('plan_exceptions')
    op.drop_table('plan_actions')
    # ### end Alembic commands ###
