"""add capacity_delay_days to work orders

Revision ID: 9c9bc2939a00
Revises: 47bc518fc526
Create Date: 2026-08-22 15:48:02.753653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9bc2939a00'
down_revision: Union[str, Sequence[str], None] = '47bc518fc526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('capacity_delay_days', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'capacity_delay_days')
    # ### end Alembic commands ###
