"""initial schema

Revision ID: a78cafe12dbe
Revises: 
Create Date: 2026-08-12 18:06:35.837366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78cafe12dbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('item_type', sa.Enum('RAW_MATERIAL', 'PURCHASED_COMPONENT', 'MANUFACTURED_PART', 'SUBASSEMBLY', 'FINISHED_PACKAGE', name='itemtype'), nullable=False),
    sa.Column('make_or_buy', sa.Enum('MAKE', 'BUY', name='makeorbuy'), nullable=False),
    sa.Column('uom', sa.String(length=10), nullable=False),
    sa.Column('standard_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('default_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_project_item', sa.Boolean(), nullable=False),
    sa.Column('is_aftermarket_item', sa.Boolean(), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reorder_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('safety_stock', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('machine_types',
    sa.Column('machine_type_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('avg_engineering_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('avg_assembly_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('avg_test_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('avg_shared_machining_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('avg_lead_time_weeks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('machine_type_id')
    )
    op.create_table('overhaul_jobs',
    sa.Column('job_id', sa.String(length=30), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'TEARDOWN', 'INSPECTION', 'AWAITING_APPROVAL', 'APPROVED', 'IN_REPAIR', 'TEST', 'COMPLETE', name='overhauljobstatus'), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('plants',
    sa.Column('plant_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('plant_id')
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('reliability_rating', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('boms',
    sa.Column('bom_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_item_id', sa.String(length=30), nullable=False),
    sa.Column('bom_type', sa.Enum('PROJECT_TEMPLATE', 'PROJECT_INSTANCE', 'STANDARD', name='bomtype'), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['parent_item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('bom_id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('qty_on_hand', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('qty_allocated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.String(length=20), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overhaul_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.String(length=30), nullable=False),
    sa.Column('recommended_action', sa.Enum('REPLACE', 'REPAIR', 'REUSE', name='findingaction'), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MAKE', 'BUY', 'INVENTORY', name='findingsource'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['overhaul_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'RELEASED', 'RECEIVED', 'CANCELLED', name='purchaseorderstatus'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_table('routings',
    sa.Column('routing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=30), nullable=False),
    sa.Column('routing_type', sa.Enum('NEW_UNIT', 'AFTERMARKET_MFG', 'OVERHAUL', name='routingtype'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('routing_id')
    )
    op.create_table('sales_orders',
    sa.Column('order_id', sa.String(length=30), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('item_id', sa.String(length=30), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Enum('STANDARD', 'EMERGENCY', name='salesordertype'), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('work_centers',
    sa.Column('work_center_id', sa.String(length=20), nullable=False),
    sa.Column('plant_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('area', sa.Enum('NEW_UNIT', 'AFTERMARKET', 'SHARED', name='workcenterarea'), nullable=False),
    sa.Column('capacity_uom', sa.String(length=20), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.plant_id'], ),
    sa.PrimaryKeyConstraint('work_center_id')
    )
    op.create_table('bom_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('component_item_id', sa.String(length=30), nullable=False),
    sa.Column('qty_per', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('scrap_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.bom_id'], ),
    sa.ForeignKeyConstraint(['component_item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capacity_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_center_id', sa.String(length=20), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('available_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.work_center_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=30), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('project_type', sa.Enum('ETO', 'CTO', name='projecttype'), nullable=False),
    sa.Column('machine_type_id', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('QUOTED', 'FIRM', 'LOST', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('contract_due_date', sa.Date(), nullable=True),
    sa.Column('project_instance_bom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_type_id'], ['machine_types.machine_type_id'], ),
    sa.ForeignKeyConstraint(['project_instance_bom_id'], ['boms.bom_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.String(length=30), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.po_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('work_center_id', sa.String(length=20), nullable=False),
    sa.Column('setup_time_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('run_time_hours_per_unit', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['routing_id'], ['routings.routing_id'], ),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.work_center_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_orders',
    sa.Column('wo_id', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.String(length=30), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('PROJECT', 'AFTERMARKET', 'OVERHAUL', name='workordersource'), nullable=False),
    sa.Column('source_ref', sa.String(length=30), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'RELEASED', 'IN_PROGRESS', 'COMPLETE', 'CANCELLED', name='workorderstatus'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['routing_id'], ['routings.routing_id'], ),
    sa.PrimaryKeyConstraint('wo_id')
    )
    op.create_table('project_milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=30), nullable=False),
    sa.Column('milestone_name', sa.String(length=100), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_milestones')
    op.drop_table('work_orders')
    op.drop_table('routing_operations')
    op.drop_table('purchase_order_lines')
    op.drop_table('projects')
    op.drop_table('capacity_calendar')
    op.drop_table('bom_lines')
    op.drop_table('work_centers')
    op.drop_table('sales_orders')
    op.drop_table('routings')
    op.drop_table('purchase_orders')
    op.drop_table('overhaul_findings')
    op.drop_table('item_suppliers')
    op.drop_table('inventory')
    op.drop_table('boms')
    op.drop_table('suppliers')
    op.drop_table('plants')
    op.drop_table('overhaul_jobs')
    op.drop_table('machine_types')
    op.drop_table('items')
    # ### end Alembic commands ###
