"""add revenue fields to sales_orders and overhaul_jobs

Revision ID: b701f93ba9a3
Revises: a78cafe12dbe
Create Date: 2026-08-12 18:10:46.098756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b701f93ba9a3'
down_revision: Union[str, Sequence[str], None] = 'a78cafe12dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overhaul_jobs', sa.Column('estimated_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('sales_orders', sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'unit_price')
    op.drop_column('overhaul_jobs', 'estimated_value')
    # ### end Alembic commands ###
