"""Gather independent demand from the three sources: firm projects, aftermarket
sales orders, and approved overhaul findings. Everything below this is
dependent demand, generated by BOM explosion in explode.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta

from sqlalchemy.orm import Session

from app.models.enums import (
    FindingAction,
    FindingSource,
    OverhaulJobStatus,
    ProjectStatus,
    WorkOrderSource,
)
from app.models.overhaul import OverhaulFinding, OverhaulJob
from app.models.aftermarket import SalesOrder
from app.models.project import Project

# Overhaul jobs don't carry an explicit due date (the domain model treats
# AWAITING_APPROVAL as an open-ended hold) — approximate urgency by stage
# instead, consistent with the "lead time is critical" nature of turnaround work.
OVERHAUL_URGENCY_DAYS = {
    OverhaulJobStatus.APPROVED: 14,
    OverhaulJobStatus.IN_REPAIR: 7,
    OverhaulJobStatus.TEST: 3,
}


@dataclass
class Demand:
    item_id: str
    qty: float
    need_date: date
    source: WorkOrderSource
    source_ref: str
    priority: int = 5  # lower = more urgent; used for capacity-conflict reporting, not scheduling math


def gather_demand(db: Session, today: date) -> list[Demand]:
    demands: list[Demand] = []

    # Only plan demand that isn't already in the past — a synthetic dataset
    # spans trailing history too, and orders/projects with a due date already
    # behind "today" represent closed/shipped backlog, not open demand. There's
    # no explicit fulfilled/shipped status on these tables yet (phase-1
    # simplification); date filtering is the stand-in.
    projects = db.query(Project).filter(
        Project.status == ProjectStatus.FIRM,
        Project.project_instance_bom_id.isnot(None),
        Project.contract_due_date >= today,
    ).all()
    for p in projects:
        demands.append(Demand(
            item_id=f"FG-{p.project_id}", qty=1, need_date=p.contract_due_date,
            source=WorkOrderSource.PROJECT, source_ref=p.project_id, priority=3,
        ))

    orders = db.query(SalesOrder).filter(SalesOrder.requested_date >= today).all()
    for o in orders:
        demands.append(Demand(
            item_id=o.item_id, qty=float(o.qty), need_date=o.requested_date,
            source=WorkOrderSource.AFTERMARKET, source_ref=o.order_id, priority=o.priority,
        ))

    jobs = db.query(OverhaulJob).filter(
        OverhaulJob.status.in_(list(OVERHAUL_URGENCY_DAYS.keys()))
    ).all()
    job_by_id = {j.job_id: j for j in jobs}
    findings = db.query(OverhaulFinding).filter(
        OverhaulFinding.job_id.in_(job_by_id.keys()),
        OverhaulFinding.recommended_action.in_([FindingAction.REPLACE, FindingAction.REPAIR]),
        OverhaulFinding.source.in_([FindingSource.MAKE, FindingSource.BUY]),
    ).all()
    for f in findings:
        job = job_by_id[f.job_id]
        urgency_days = OVERHAUL_URGENCY_DAYS[job.status]
        demands.append(Demand(
            item_id=f.item_id, qty=float(f.qty), need_date=today + timedelta(days=urgency_days),
            source=WorkOrderSource.OVERHAUL, source_ref=job.job_id, priority=2,
        ))

    return demands


def _week_start(d: date) -> date:
    return d - timedelta(days=d.weekday())


def bucket_demand(demands: list[Demand]) -> list[Demand]:
    """Batch same-item demand from the same source and urgency within the same
    week into one combined demand record.

    Without this, every individual sales order becomes its own work order and
    pays a full machining setup (hours, independent of quantity) on its own —
    unrealistic (a real shop batches same-part runs) and it swamps shared
    work centers with setup overhead rather than genuine run-time load.

    Priority is part of the key, not just item/source/week. Batching a rush
    turnaround order together with routine stock replenishment would drag the
    whole batch onto the rush date, making dozens of relaxed orders look
    critically late and inflating apparent urgency. A shop runs the hot job
    separately; so does this.
    """
    buckets: dict[tuple[str, WorkOrderSource, int, date], list[Demand]] = {}
    for d in demands:
        key = (d.item_id, d.source, d.priority, _week_start(d.need_date))
        buckets.setdefault(key, []).append(d)

    bucketed: list[Demand] = []
    for (item_id, source, _priority, _week), group in buckets.items():
        total_qty = sum(g.qty for g in group)
        earliest_need = min(g.need_date for g in group)
        best_priority = min(g.priority for g in group)
        if len(group) == 1:
            source_ref = group[0].source_ref
        else:
            source_ref = f"{group[0].source_ref} +{len(group) - 1} more"
        bucketed.append(Demand(item_id=item_id, qty=total_qty, need_date=earliest_need,
                                source=source, source_ref=source_ref, priority=best_priority))
    return bucketed
